# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(paws.storage)
    library(stats)
    library(workflows)
}
b <- board_s3(bucket = "sagemaker-us-east-2-075258722956")
v <- vetiver_pin_read(b, "lm_model", version = "20221211T210245Z-9354a")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, type = "class", path = "/invocations", debug = TRUE)
}
